/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _A3_H_RPCGEN
#define _A3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *s;

struct newString {
	s content;
};
typedef struct newString newString;

struct newList {
	int size;
	int arr[50];
};
typedef struct newList newList;

struct listValues {
	newList l1;
	newList l2;
};
typedef struct listValues listValues;

struct newComplex {
	float real;
	float img;
};
typedef struct newComplex newComplex;

struct complexValues {
	newComplex c1;
	newComplex c2;
};
typedef struct complexValues complexValues;

#define A3 0x40000002
#define A3PROG 1

#if defined(__STDC__) || defined(__cplusplus)
#define hostname 1
extern  newString * hostname_1(void *, CLIENT *);
extern  newString * hostname_1_svc(void *, struct svc_req *);
#define mergeSort 2
extern  newList * mergesort_1(listValues *, CLIENT *);
extern  newList * mergesort_1_svc(listValues *, struct svc_req *);
#define encryptedEcho 3
extern  newString * encryptedecho_1(newString *, CLIENT *);
extern  newString * encryptedecho_1_svc(newString *, struct svc_req *);
#define listFiles 4
extern  newString * listfiles_1(void *, CLIENT *);
extern  newString * listfiles_1_svc(void *, struct svc_req *);
#define addComplex 5
extern  newComplex * addcomplex_1(complexValues *, CLIENT *);
extern  newComplex * addcomplex_1_svc(complexValues *, struct svc_req *);
extern int a3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define hostname 1
extern  newString * hostname_1();
extern  newString * hostname_1_svc();
#define mergeSort 2
extern  newList * mergesort_1();
extern  newList * mergesort_1_svc();
#define encryptedEcho 3
extern  newString * encryptedecho_1();
extern  newString * encryptedecho_1_svc();
#define listFiles 4
extern  newString * listfiles_1();
extern  newString * listfiles_1_svc();
#define addComplex 5
extern  newComplex * addcomplex_1();
extern  newComplex * addcomplex_1_svc();
extern int a3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_s (XDR *, s*);
extern  bool_t xdr_newString (XDR *, newString*);
extern  bool_t xdr_newList (XDR *, newList*);
extern  bool_t xdr_listValues (XDR *, listValues*);
extern  bool_t xdr_newComplex (XDR *, newComplex*);
extern  bool_t xdr_complexValues (XDR *, complexValues*);

#else /* K&R C */
extern bool_t xdr_s ();
extern bool_t xdr_newString ();
extern bool_t xdr_newList ();
extern bool_t xdr_listValues ();
extern bool_t xdr_newComplex ();
extern bool_t xdr_complexValues ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_A3_H_RPCGEN */
