/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "A3.h"


void
a3_1(char *host)
{
	CLIENT *clnt;
	newString  *result_1;
	char *hostname_1_arg;
	newList  *result_2;
	listValues  mergesort_1_arg;
	newString  *result_3;
	newString  encryptedecho_1_arg;
	newString  *result_4;
	char *listfiles_1_arg;
	newComplex  *result_5;
	complexValues  addcomplex_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, A3, A3PROG, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int choice;
	char c[100];
	// loop continues to run until the client selects exit option or the client fails
	while(1){
		printf("Select any one option:\n 1. hostname \n 2. mergeSort \n 3. encryptedEcho \n 4. listFiles \n 5. addComplex \n 6. Exit \n");
		scanf("%d",&choice);
		if(choice == 1){ // choice 1 . hostname – Returns the hostname on which the server is running.
			result_1 = hostname_1((void*)&hostname_1_arg, clnt);
			if (result_1 == (newString *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("\n The hostname is: %s \n",result_1->content);
			}
		}else if(choice == 2){ // choice 2. mergeSort – Accepts two integer lists and returns their merged list that is sorted.
			printf("\n Input List Size for List 1\n");
			scanf("%d",&mergesort_1_arg.l1.size);
			int i=0;
			for(i=0; i<mergesort_1_arg.l1.size;i++){
				printf("\n Input Integer %d: ",i+1);
				scanf("%d",&mergesort_1_arg.l1.arr[i]);
			}
			printf("\n Input List Size for List 2\n");
			scanf("%d",&mergesort_1_arg.l2.size);
	
			for(i=0; i<mergesort_1_arg.l2.size;i++){
				printf("\n Input Integer %d: ",i+1);
				scanf("%d",&mergesort_1_arg.l2.arr[i]);
			}

			result_2 = mergesort_1(&mergesort_1_arg, clnt);
			if (result_2 == (newList *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("\n The merge sorted list is: %s \n");
				int i;
				for(i=0; i<result_2->size;i++){
				printf(" %d ",result_2->arr[i]);
				}
				printf("\n");
			}

		}else if(choice == 3){ //choice 3  encryptedEcho – Returns an encrypted version (using any technique) of whatever a Client
					//sends as an input. You will need to indicate your technique in the report.
			printf("\n Input String\n");
			scanf(" %[^\t\n]s",&c);
			encryptedecho_1_arg.content = c;
			result_3 = encryptedecho_1(&encryptedecho_1_arg, clnt);
			if (result_3 == (newString *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("\n The encryptedecho is: %s \n",result_3->content);	
			}
		}else if(choice == 4){ // choice 4. listFiles – Returns a list of all files in the current directory
			result_4 = listfiles_1((void*)&listfiles_1_arg, clnt);
			if (result_4 == (newString *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("\n A list of all files in the current directory: %s \n",result_4->content);	
			}
		}else if(choice == 5){ // choice 5. addComplex – Accepts two complex numbers and returns their sum.
			printf("\n Input Complex 1\n");
			printf("\n Input Complex 1 - real part\n");
			scanf("%f",&addcomplex_1_arg.c1.real);
			printf("\n Input Complex 1 - imaginary part\n");
			scanf("%f",&addcomplex_1_arg.c1.img);
			printf("\n Input Complex 2\n");
			printf("\n Input Complex 2 - real part\n");
			scanf("%f",&addcomplex_1_arg.c2.real);
			printf("\n Input Complex 2 - imaginary part\n");
			scanf("%f",&addcomplex_1_arg.c2.img);
			result_5 = addcomplex_1(&addcomplex_1_arg, clnt);
			if (result_5 == (newComplex *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("\n Addition of the complex is %f + %fi\n",result_5->real,result_5->img);
			}

		}else if(choice == 6){ // choice 6. Exit the system
			printf("\n You chose exit option\n");
			break;
		}else{ // wrong input
			printf("\n Wrong input, please try again\n");
		}

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	a3_1 (host);
exit (0);
}
