/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "A3.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

newString *
hostname_1(void *argp, CLIENT *clnt)
{
	static newString clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, hostname,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_newString, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

newList *
mergesort_1(listValues *argp, CLIENT *clnt)
{
	static newList clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, mergeSort,
		(xdrproc_t) xdr_listValues, (caddr_t) argp,
		(xdrproc_t) xdr_newList, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

newString *
encryptedecho_1(newString *argp, CLIENT *clnt)
{
	static newString clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, encryptedEcho,
		(xdrproc_t) xdr_newString, (caddr_t) argp,
		(xdrproc_t) xdr_newString, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

newString *
listfiles_1(void *argp, CLIENT *clnt)
{
	static newString clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, listFiles,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_newString, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

newComplex *
addcomplex_1(complexValues *argp, CLIENT *clnt)
{
	static newComplex clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, addComplex,
		(xdrproc_t) xdr_complexValues, (caddr_t) argp,
		(xdrproc_t) xdr_newComplex, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
