/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "A3.h"

bool_t
xdr_s (XDR *xdrs, s *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 10000))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_newString (XDR *xdrs, newString *objp)
{
	register int32_t *buf;

	 if (!xdr_s (xdrs, &objp->content))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_newList (XDR *xdrs, newList *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  50 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->size);
			{
				register int *genp;

				for (i = 0, genp = objp->arr;
					i < 50; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  50 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->size = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->arr;
					i < 50; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listValues (XDR *xdrs, listValues *objp)
{
	register int32_t *buf;

	 if (!xdr_newList (xdrs, &objp->l1))
		 return FALSE;
	 if (!xdr_newList (xdrs, &objp->l2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_newComplex (XDR *xdrs, newComplex *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->real))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->img))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_complexValues (XDR *xdrs, complexValues *objp)
{
	register int32_t *buf;

	 if (!xdr_newComplex (xdrs, &objp->c1))
		 return FALSE;
	 if (!xdr_newComplex (xdrs, &objp->c2))
		 return FALSE;
	return TRUE;
}
